# Generated by Django 6.0.1 on 2026-01-25 20:48
from django.db import migrations


def seed_difficulties(apps, schema_editor):
    Difficulty = apps.get_model("platform_web", "Difficulty")

    data = [
        ("easy", "Easy"),
        ("moderate", "Moderate"),
        ("hard", "Hard"),
        ("extreme", "Hardcore"),
        ("You can do this", "You can do this"),
        ("Some effort required", "Some effort required"),
        ("Challenging", "Challenging"),
        ("For experts only", "For experts only"),
    ]

    for name, _ in data:
        Difficulty.objects.get_or_create(name=name)


def unseed_difficulties(apps, schema_editor):
    Difficulty = apps.get_model("platform_web", "Difficulty")
    Difficulty.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_difficulties, unseed_difficulties),
    ]
