# Generated by Django 6.0.1 on 2026-01-25
from django.db import migrations


def seed_frameworks(apps, schema_editor):
    Framework = apps.get_model("platform_web", "Framework")
    frameworks = [
        ("Vue", 1),
        ("React", 2),
        ("FastAPI", 3),
        ("Django", 4),
        ("WordPress", 5),
        ("Laravel", 6),
        ("Express", 7),
        ("Spring", 8),
    ]
    for name, order in frameworks:
        Framework.objects.get_or_create(name=name, defaults={"order": order})


def unseed_frameworks(apps, schema_editor):
    Framework = apps.get_model("platform_web", "Framework")
    Framework.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0002_seed_difficulties"),
    ]

    operations = [
        migrations.RunPython(seed_frameworks, unseed_frameworks),
    ]
