# Generated by Django 6.0.1 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_token_verified',
            field=models.BooleanField(default=False),
        ),
    ]
