# Generated by Django 6.0.1 on 2026-03-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_is_token_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
