# Generated by Django 6.0.1 on 2026-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interface_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian')], default='', max_length=10),
        ),
    ]
