# Generated by Django 6.0.1 on 2026-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_interface_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wakatime_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
