# Generated by Django 6.0.1 on 2026-06-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_interface_language'),
        ('platform_web', '0055_paidplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to='platform_web.paidplan'),
        ),
    ]
