# Generated by Django 6.0.1 on 2026-01-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('extreme', 'Hardcore'), ('You can do this', 'You can do this'), ('Some effort required', 'Some effort required'), ('Challenging', 'Challenging'), ('For experts only', 'For experts only')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'difficulties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vue', 'Vue'), ('React', 'React'), ('Django', 'Django'), ('WordPress', 'WordPress'), ('Laravel', 'Laravel'), ('Express', 'Express'), ('Spring', 'Spring'), ('FastAPI', 'FastAPI')], max_length=20, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying frameworks (lower comes first)')),
            ],
            options={
                'db_table': 'frameworks',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'project_parts',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML/CSS', 'HTML/CSS'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('PHP', 'PHP'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Scala', 'Scala'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('Perl', 'Perl'), ('Haskell', 'Haskell'), ('Elixir', 'Elixir'), ('Clojure', 'Clojure'), ('Shell', 'Shell')], max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying programming languages (lower comes first)')),
            ],
            options={
                'db_table': 'programming_languages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying skills (lower comes first)')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML/CSS: UI development', 'HTML/CSS: UI development'), ('JavaScript: interactivity, client logic', 'JavaScript: interactivity, client logic'), ('Backend: server logic, database', 'Backend: server logic, database'), ('Deployment: deployment and maintenance', 'Deployment: deployment and maintenance')], max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'development_stages',
            },
        ),
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Zay', max_length=255)),
                ('tagline', models.CharField(default='Gadgets that love you', max_length=255)),
            ],
            options={
                'verbose_name': 'Website Configuration',
                'verbose_name_plural': 'Website Configuration',
            },
        ),
        migrations.CreateModel(
            name='ChapterPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_title', models.CharField(blank=True, help_text='Override the part title for this chapter context.', max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_parts', to='platform_web.chapter')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_links', to='platform_web.part')),
            ],
            options={
                'db_table': 'chapter_parts',
                'ordering': ['order'],
                'unique_together': {('chapter', 'part')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='parts',
            field=models.ManyToManyField(related_name='chapter_set', through='platform_web.ChapterPart', to='platform_web.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='languages',
            field=models.ManyToManyField(blank=True, to='platform_web.programminglanguage'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('languages', models.ManyToManyField(blank=True, related_name='courses', to='platform_web.programminglanguage')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='platform_web.course')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_web.difficulty')),
                ('framework', models.ManyToManyField(blank=True, help_text='Predefined frameworks', to='platform_web.framework', verbose_name='Frameworks')),
                ('programming_languages', models.ManyToManyField(blank=True, help_text='Predefined programming languages', to='platform_web.programminglanguage')),
                ('skills', models.ManyToManyField(blank=True, to='platform_web.skill')),
                ('stages', models.ManyToManyField(blank=True, to='platform_web.stage')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='parts', to='platform_web.project'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='platform_web.project'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='platform_web.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='platform_web.submission')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='telegram', max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('website_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_web.websiteconfig')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
