# Generated by Django 5.2.9 on 2026-01-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0003_developmentstage_difficulty_skill_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_web.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_web.skill')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'skill')},
            },
        ),
    ]
