# Generated by Django 6.0.1 on 2026-01-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0003_seed_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(choices=[('Vue', 'Vue'), ('React', 'React'), ('Django', 'Django'), ('WordPress', 'WordPress'), ('Laravel', 'Laravel'), ('Express', 'Express'), ('Spring', 'Spring'), ('FastAPI', 'FastAPI')], max_length=20, unique=True),
        ),
    ]
