# Generated by Django 5.2.9 on 2026-01-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0004_remove_project_description_remove_project_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
