# Generated by Django 6.0.1 on 2026-01-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0004_alter_framework_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying programming languages (lower comes first)'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(choices=[('HTML/CSS', 'HTML/CSS'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('PHP', 'PHP'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Scala', 'Scala'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('Perl', 'Perl'), ('Haskell', 'Haskell'), ('Elixir', 'Elixir'), ('Clojure', 'Clojure'), ('Shell', 'Shell')], max_length=50, unique=True),
        ),
    ]
