# Generated by Django 6.0.1 on 2026-01-25
from django.db import migrations
from django.utils.text import slugify


def seed_programming_languages(apps, schema_editor):
    ProgrammingLanguage = apps.get_model("platform_web", "ProgrammingLanguage")
    languages = [
        ("HTML/CSS", 1),
        ("JavaScript", 2),
        ("Python", 3),
        ("PHP", 4),
        ("Java", 5),
        ("C++", 6),
        ("C#", 7),
        ("Ruby", 8),
        ("Go", 9),
        ("Swift", 10),
        ("Kotlin", 11),
        ("Rust", 12),
        ("Scala", 13),
        ("Dart", 14),
        ("Objective-C", 15),
        ("Perl", 16),
        ("Haskell", 17),
        ("Elixir", 18),
        ("Clojure", 19),
        ("Shell", 20),
    ]

    # Map tricky names to safe unique slugs
    slug_map = {"C#": "c-sharp", "C++": "c-plus-plus", "Objective-C": "objective-c"}

    for name, order in languages:
        slug = slug_map.get(name, slugify(name))
        ProgrammingLanguage.objects.create(name=name, order=order, slug=slug)


def unseed_programming_languages(apps, schema_editor):
    ProgrammingLanguage = apps.get_model("platform_web", "ProgrammingLanguage")
    ProgrammingLanguage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0005_alter_programminglanguage_options_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_programming_languages, unseed_programming_languages),
    ]
