# Generated by Django 6.0.1 on 2026-01-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0006_seed_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('HTML/CSS: UI, UX', 'HTML/CSS: UI, UX'), ('JavaScript: client, interactivity', 'JavaScript: client, interactivity'), ('Backend: server, database', 'Backend: server, database'), ('Refactoring', 'Refactoring'), ('Deployment', 'Deployment'), ('Tests', 'Tests')], max_length=100, unique=True),
        ),
    ]
