# Generated by Django 5.2.9 on 2026-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0006_alter_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying skills (lower comes first)'),
        ),
        migrations.DeleteModel(
            name='ProjectSkill',
        ),
    ]
