# Generated by Django 6.0.1 on 2026-01-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0007_seed_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='platform_web.project'),
        ),
    ]
