# Generated by Django 6.0.1 on 2026-01-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0007_seed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='codepen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of lesson objectives'),
        ),
    ]
