# Generated by Django 6.0.1 on 2026-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0008_seed_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Desktop Applications', 'Desktop Applications'), ('Mobile Applications', 'Mobile Applications'), ('Telegram Bots', 'Telegram Bots'), ('Data Science', 'Data Science'), ('Security', 'Security'), ('HTML & CSS', 'HTML & CSS Fundamentals'), ('JavaScript Basics', 'JavaScript Basics'), ('Advanced JavaScript', 'Advanced JavaScript'), ('Vue.js Crash Course', 'Vue.js Crash Course'), ('React for Beginners', 'React for Beginners'), ('APIs with FastAPI', 'APIs with FastAPI'), ('Django Essentials', 'Django Essentials'), ('Python for Web Development', 'Python for Web Development'), ('Database Design & SQL', 'Database Design & SQL'), ('Testing & Debugging', 'Testing & Debugging'), ('Deployment & DevOps', 'Deployment & DevOps'), ('Version Control with Git', 'Version Control with Git'), ('UI/UX Design Principles', 'UI/UX Design Principles'), ('Backend Development with Node.js', 'Backend Development with Node.js'), ('Full Stack Web Development', 'Full Stack Web Development')], max_length=255, unique=True),
        ),
    ]
