# Generated by Django 6.0.1 on 2026-01-29 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('platform_web', '0008_part_codepen_url_part_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
