# Generated by Django 6.0.1 on 2026-01-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0009_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('topic', 'Topic'), ('project', 'Project')], default='topic', max_length=20),
        ),
    ]
