# Generated by Django 6.0.1 on 2026-01-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0010_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='projects',
        ),
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='platform_web.project'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='parts',
        ),
        migrations.DeleteModel(
            name='ChapterPart',
        ),
    ]
