# Generated by Django 6.0.1 on 2026-01-27
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('platform_web', '0011_remove_part_projects_part_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='chapter_set', to='platform_web.part'),
        ),
    ]
