# Generated by Django 6.0.1 on 2026-01-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0011_remove_part_projects_part_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_parts', to='platform_web.chapter')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_links', to='platform_web.part')),
            ],
            options={
                'db_table': 'chapter_parts',
                'ordering': ['order'],
                'unique_together': {('chapter', 'part')},
            },
        ),
    ]
