# Generated by Django 6.0.1 on 2026-01-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0012_chapterpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='chapter_set', through='platform_web.ChapterPart', to='platform_web.part'),
        ),
    ]
