# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    model_names = [
        "Chapter",
        "Course",
        "Difficulty",
        "Framework",
        "Part",
        "ProgrammingLanguage",
        "Review",
        "Skill",
        "Stage",
        "Submission",
    ]
    for model_name in model_names:
        Model = apps.get_model("platform_web", model_name)
        for row in Model.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("platform_web", "0012_chapter_uuid_course_uuid_difficulty_uuid_and_more"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]