# Generated by Django 6.0.1 on 2026-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0014_auto_20260129_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description for the Dashboard'),
        ),
        migrations.AddField(
            model_name='project',
            name='stages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
