# Generated by Django 6.0.1 on 2026-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0015_project_description_remove_project_stages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
