# Generated by Django 6.0.1 on 2026-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0016_alter_project_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at', 'title']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='project',
            name='course_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='language_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
