# Generated by Django 6.0.1 on 2026-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0017_alter_project_options_remove_project_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-updated_at', 'title']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering for admin sorting'),
        ),
    ]
