# Generated by Django 6.0.1 on 2026-02-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0018_alter_project_options_project_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='Lesson',
        ),
    ]
