# Generated by Django 6.0.1 on 2026-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0019_rename_part_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, choices=[('theory', 'Theory'), ('video', 'Video'), ('exercise', 'Exercise'), ('mini-project', 'Mini-project'), ('project', 'Project')], max_length=50, null=True),
        ),
    ]
