# Generated by Django 6.0.1 on 2026-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0020_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, choices=[('theory', 'Theory'), ('video', 'Video'), ('exercise', 'Exercise'), ('task', 'Task'), ('mini-project', 'Mini-project'), ('project', 'Project')], max_length=50, null=True),
        ),
    ]
