# Generated by Django 6.0.1 on 2026-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0021_alter_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codepen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
