# Generated by Django 6.0.1 on 2026-02-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0022_project_codepen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
