# Generated by Django 6.0.1 on 2026-02-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0023_lesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
