# Generated by Django 6.0.1 on 2026-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0025_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
