# Generated by Django 6.0.1 on 2026-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0026_alter_difficulty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
