# Generated by Django 6.0.2 on 2026-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0027_difficulty_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='framework',
            name='order',
            field=models.PositiveIntegerField(default=5, help_text='Order for displaying frameworks'),
        ),
    ]
