# Generated by Django 6.0.1 on 2026-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0028_alter_difficulty_options_alter_framework_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
