# Generated by Django 6.0.1 on 2026-03-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0029_lesson_last_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
