# Generated by Django 6.0.1 on 2026-03-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0030_remove_lesson_chapter_delete_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='part',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
