# Generated by Django 6.0.1 on 2026-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0031_remove_review_submission_remove_project_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='tagline_en',
            field=models.CharField(default='Gadgets that love you', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='tagline_ru',
            field=models.CharField(default='Gadgets that love you', max_length=255, null=True),
        ),
    ]
