# Generated by Django 6.0.1 on 2026-03-28 08:13

from django.db import migrations, models
from platform_web.models.app.project.Course import Course


def copy_titles(apps, schema_editor):
    Course = apps.get_model("platform_web", "Course")
    for course in Course.objects.all():
        course.title_en = course.title
        course.title_ru = course.title
        course.save(update_fields=["title_en", "title_ru"])


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0032_websiteconfig_tagline_en_websiteconfig_tagline_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(copy_titles),
        migrations.AlterField(
            model_name="course",
            name="title_en",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_ru",
            field=models.CharField(max_length=255),
        ),
    ]
