# Generated by Django 6.0.1 on 2026-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0033_fix_course_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
