# Generated by Django 6.0.1 on 2026-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0034_alter_course_title_en_alter_course_title_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-updated_at']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS project_parts_languages;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='lesson',
                    name='languages',
                ),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE UNIQUE INDEX IF NOT EXISTS courses_title_en_7e4a2da0_uniq ON courses (title_en);',
                    reverse_sql='DROP INDEX IF EXISTS courses_title_en_7e4a2da0_uniq;',
                ),
                migrations.RunSQL(
                    sql='CREATE UNIQUE INDEX IF NOT EXISTS courses_title_ru_7c51e8d9_uniq ON courses (title_ru);',
                    reverse_sql='DROP INDEX IF EXISTS courses_title_ru_7c51e8d9_uniq;',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='course',
                    name='title_en',
                    field=models.CharField(max_length=255, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='course',
                    name='title_ru',
                    field=models.CharField(max_length=255, null=True, unique=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('topic', 'Topic'), ('project', 'Project'), ('guide', 'Guide')], default='topic', max_length=20),
        ),
    ]
