# Generated by Django 6.0.1 on 2026-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0037_project_language_default_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_video_course',
            field=models.BooleanField(default=False),
        ),
    ]
