# Generated by Django 6.0.1 on 2026-04-07 14:40

import platform_web.models.base.Changelog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0038_project_is_video_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Format: major.minor.patch (e.g. 1.4.46)', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('changes', models.TextField(help_text='Bulleted list of changes. Each line is a separate bullet.')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Changelog',
                'verbose_name_plural': 'Changelogs',
                'db_table': 'changelog',
                'ordering': ['-released_at'],
            },
        ),
    ]
