# Generated by Django 6.0.1 on 2026-04-07 14:54

import platform_web.models.base.Changelog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0039_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='version',
            field=models.CharField(help_text='Format: major.minor.patch (e.g. 1.4.46)', max_length=20, unique=True, validators=[platform_web.models.base.Changelog.validate_version]),
        ),
    ]
