# Generated by Django 6.0.1 on 2026-04-08 00:00

import json

from django.db import migrations, models
from django.utils.html import escape


def _list_to_html(items):
    cleaned = [str(item).strip() for item in items if str(item).strip()]
    if not cleaned:
        return ""
    return "<ol>" + "".join(f"<li>{escape(item)}</li>" for item in cleaned) + "</ol>"


def migrate_stages_to_html(apps, schema_editor):
    Project = apps.get_model("platform_web", "Project")

    for project in Project.objects.all().iterator():
        raw = project.stages

        if raw in (None, "", []):
            html_value = ""
        elif isinstance(raw, list):
            html_value = _list_to_html(raw)
        elif isinstance(raw, str):
            raw_str = raw.strip()
            if not raw_str or raw_str == "[]":
                html_value = ""
            elif raw_str.startswith("<"):
                # Assume already formatted HTML content.
                html_value = raw
            else:
                try:
                    parsed = json.loads(raw_str)
                except (TypeError, ValueError):
                    parsed = None

                if isinstance(parsed, list):
                    html_value = _list_to_html(parsed)
                elif isinstance(parsed, str):
                    parsed_str = parsed.strip()
                    html_value = parsed if parsed_str.startswith("<") else f"<p>{escape(parsed_str)}</p>"
                else:
                    html_value = f"<p>{escape(raw_str)}</p>"
        else:
            # Keep unexpected structures readable instead of dropping data.
            html_value = f"<pre>{escape(json.dumps(raw, ensure_ascii=False))}</pre>"

        if project.stages != html_value:
            project.stages = html_value
            project.save(update_fields=["stages"])


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0041_alter_changelog_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="stages",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.RunPython(migrate_stages_to_html, migrations.RunPython.noop),
    ]
