# Generated by Django 6.0.1 on 2026-04-08 11:35

import platform_web.models.base.Changelog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0042_project_stages_json_to_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='version',
            field=models.CharField(help_text='Format: major.minor.patch (e.g. 1.4.46)', max_length=20, unique=True),
        ),
    ]
