# Generated by Django 6.0.1 on 2026-04-09 11:57

from django.db import migrations, models


def backfill_difficulty_names(apps, schema_editor):
    Difficulty = apps.get_model("platform_web", "Difficulty")

    difficulties = list(Difficulty.objects.all())
    for difficulty in difficulties:
        difficulty.name_en = difficulty.name
        difficulty.name_ru = difficulty.name

    if difficulties:
        Difficulty.objects.bulk_update(difficulties, ["name_en", "name_ru"])


def clear_backfilled_difficulty_names(apps, schema_editor):
    Difficulty = apps.get_model("platform_web", "Difficulty")
    Difficulty.objects.update(name_en=None, name_ru=None)


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0044_lesson_objectives_json_to_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_difficulty_names,
            clear_backfilled_difficulty_names,
        ),
    ]
