# Generated by Django 6.0.1 on 2026-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0045_difficulty_name_en_difficulty_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский')], default='ru', max_length=50, null=True),
        ),
    ]
