# Generated by Django 6.0.1 on 2026-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0047_backfill_seo_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, choices=[('theory', 'Theory'), ('video', 'Video'), ('exercise', 'Exercise'), ('task', 'Task'), ('mini-project', 'Mini-project'), ('project', 'Project')], default='theory', max_length=50),
        ),
    ]
