# Generated by Django 6.0.1 on 2026-05-07 08:43

from django.db import migrations

SUFFIX = " | CodeLevels"


def _strip_suffix(value: str) -> str:
    if value and value.endswith(SUFFIX):
        return value[: -len(SUFFIX)]
    return value

def remove_suffix_from_seo_fields(apps, schema_editor):
    Project = apps.get_model("platform_web", "Project")
    Lesson = apps.get_model("platform_web", "Lesson")

    projects = Project.objects.filter(seo_title__endswith=SUFFIX)
    for project in projects:
        project.seo_title = _strip_suffix(project.seo_title)
    Project.objects.bulk_update(projects, ["seo_title"])

    projects_desc = Project.objects.filter(seo_description__endswith=SUFFIX)
    for project in projects_desc:
        project.seo_description = _strip_suffix(project.seo_description)
    Project.objects.bulk_update(projects_desc, ["seo_description"])

    lessons = Lesson.objects.filter(seo_title__endswith=SUFFIX)
    for lesson in lessons:
        lesson.seo_title = _strip_suffix(lesson.seo_title)
    Lesson.objects.bulk_update(lessons, ["seo_title"])

    lessons_desc = Lesson.objects.filter(seo_description__endswith=SUFFIX)
    for lesson in lessons_desc:
        lesson.seo_description = _strip_suffix(lesson.seo_description)
    Lesson.objects.bulk_update(lessons_desc, ["seo_description"])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0049_backfill_lesson_type_nulls'),
    ]

    operations = [
        migrations.RunPython(remove_suffix_from_seo_fields, reverse_code=migrations.RunPython.noop),
    ]
