# Generated by Django 6.0.1 on 2026-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0050_clean_seo_suffixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('not_translated', 'Not translated'), ('translated', 'Translated'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='translation_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('not_translated', 'Not translated'), ('translated', 'Translated'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='translation_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
