# Generated by Django 6.0.1 on 2026-05-28 10:04

from django.db import migrations


def backfill_primary_fields_from_en(apps, schema_editor):
    Course = apps.get_model("platform_web", "Course")
    Difficulty = apps.get_model("platform_web", "Difficulty")
    WebsiteConfig = apps.get_model("platform_web", "WebsiteConfig")

    def backfill_unique_from_en(Model, value_field, en_field, temp_prefix):
        rows = list(Model.objects.all().values("pk", value_field, en_field))
        candidates = []
        candidate_pks = set()

        for row in rows:
            target = ((row.get(en_field) or "").strip())
            current = row.get(value_field)
            if not target or current == target:
                continue
            candidates.append((row["pk"], target))
            candidate_pks.add(row["pk"])

        if not candidates:
            return

        # Real conflicts: target is already held by a row that is not moving.
        stable_values = {
            row[value_field]
            for row in rows
            if row["pk"] not in candidate_pks and row.get(value_field) is not None
        }

        movable = [(pk, target) for pk, target in candidates if target not in stable_values]
        if not movable:
            return

        # Phase 1: move candidates away to temporary unique values.
        for pk, _target in movable:
            temp_value = f"{temp_prefix}{pk}"
            Model.objects.filter(pk=pk).update(**{value_field: temp_value})

        # Phase 2: assign final English values.
        for pk, target in movable:
            Model.objects.filter(pk=pk).update(**{value_field: target})

    # Keep base title aligned with English value before dropping title_en/title_ru.
    backfill_unique_from_en(Course, "title", "title_en", "__tmp_course_")

    # Keep base name aligned with English value before dropping name_en/name_ru.
    backfill_unique_from_en(Difficulty, "name", "name_en", "_t")

    # WebsiteConfig is singleton-like; copy English tagline if available.
    for config in WebsiteConfig.objects.all().iterator():
        tagline_en = (config.tagline_en or "").strip()
        if not tagline_en or config.tagline == tagline_en:
            continue
        config.tagline = tagline_en
        config.save(update_fields=["tagline"])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0051_lesson_translated_at_lesson_translation_status_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_primary_fields_from_en,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='difficulty',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='difficulty',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='websiteconfig',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='websiteconfig',
            name='tagline_ru',
        ),
    ]
