# Generated by Django 6.0.1 on 2026-06-02 12:17
from django.db import migrations, models
from django.utils.text import slugify


def backfill_course_slugs(apps, schema_editor):
    Course = apps.get_model("platform_web", "Course")

    existing_slugs = {
        slug
        for slug in Course.objects.exclude(slug__isnull=True).values_list(
            "slug", flat=True
        )
        if slug
    }

    updates = []

    for course in Course.objects.all().iterator():
        if course.slug:
            continue

        base_slug = slugify((course.title or "").strip()) or f"course-{course.pk}"
        base_slug = base_slug[:255]
        candidate = base_slug
        counter = 2

        while candidate in existing_slugs:
            suffix = f"-{counter}"
            candidate = f"{base_slug[: 255 - len(suffix)]}{suffix}"
            counter += 1

        course.slug = candidate
        existing_slugs.add(candidate)
        updates.append(course)

    if updates:
        Course.objects.bulk_update(updates, ["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0052_remove_course_title_en_remove_course_title_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True),
        ),
        migrations.RunPython(
            backfill_course_slugs, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_slug_key;
            DROP INDEX IF EXISTS courses_slug_2136ffbe_like;
            DROP INDEX IF EXISTS courses_slug_2136ffbe_uniq;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
