# Generated by Django 6.0.1 on 2026-06-02 13:10

from django.db import migrations
from django.db.models import Q
from django.utils.text import slugify


def populate_missing_lesson_slugs(apps, schema_editor):
    Lesson = apps.get_model("platform_web", "Lesson")

    blank_slug_filter = Q(slug="") | Q(slug__isnull=True)
    lessons = Lesson.objects.filter(blank_slug_filter).only("pk", "title")
    existing_slugs = set(
        Lesson.objects.exclude(blank_slug_filter).values_list("slug", flat=True)
    )

    for lesson in lessons.iterator(chunk_size=500):
        base_slug = slugify((lesson.title or "").strip()) or f"lesson-{lesson.pk}"
        slug = base_slug

        suffix = 1
        while slug in existing_slugs:
            slug = f"{base_slug}-{suffix}"
            suffix += 1

        Lesson.objects.filter(pk=lesson.pk).update(slug=slug)
        existing_slugs.add(slug)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("platform_web", "0053_course_slug"),
    ]

    operations = [
        migrations.RunPython(
            populate_missing_lesson_slugs,
            migrations.RunPython.noop,
        ),
    ]
