# Generated by Django 6.0.1 on 2026-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0054_auto_20260602_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('access_level', models.PositiveIntegerField(default=0)),
                ('ui_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'paid_plans',
                'ordering': ['ui_order'],
            },
        ),
    ]
