# Generated by Django 6.0.1 on 2026-06-12  ??:??
from django.db import migrations


def seed_paid_plans(apps, schema_editor):
    PaidPlan = apps.get_model("platform_web", "PaidPlan")

    plans = [
        {"title": "Free", "access_level": 0, "ui_order": 0},
        {"title": "Supporter", "access_level": 1, "ui_order": 1},
        {"title": "I'm in love", "access_level": 2, "ui_order": 2},
        {"title": "Top 1%", "access_level": 3, "ui_order": 3},
    ]

    for plan_data in plans:
        PaidPlan.objects.update_or_create(
            title=plan_data["title"],
            defaults={
                "access_level": plan_data["access_level"],
                "ui_order": plan_data["ui_order"],
            },
        )


def unseed_paid_plans(apps, schema_editor):
    PaidPlan = apps.get_model("platform_web", "PaidPlan")
    PaidPlan.objects.filter(title__in=["Free", "Supporter", "I'm in love", "Top 1%"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0055_paidplan"),
    ]

    operations = [
        migrations.RunPython(seed_paid_plans, unseed_paid_plans),
    ]
