# Generated by Django 6.0.1 on 2026-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0056_seed_paid_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
