# Generated by Django 6.0.1 on 2026-06-12 08:19
from django.db import migrations


def populate_paid_plan_names(apps, schema_editor):
    PaidPlan = apps.get_model("platform_web", "PaidPlan")

    name_map = {
        "Free": "Free",
        "Supporter": "Premium",
        "I'm in love": "Pro",
        "Top 1%": "Pro+",
    }

    for title, name in name_map.items():
        PaidPlan.objects.filter(title=title).update(name=name)


def revert_paid_plan_names(apps, schema_editor):
    PaidPlan = apps.get_model("platform_web", "PaidPlan")
    PaidPlan.objects.filter(title__in=["Free", "Supporter", "I'm in love", "Top 1%"],).update(name=None)


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0057_paidplan_name"),
    ]

    operations = [
        migrations.RunPython(populate_paid_plan_names, revert_paid_plan_names),
    ]
