# Generated by Django 6.0.1 on 2026-06-12 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0058_seed_paid_plans_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='paidplan',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='paidplan_price_non_negative'),
        ),
    ]
