# Generated by Django 6.0.1 on 2026-06-12 08:19
from django.db import migrations
from decimal import Decimal

def populate_paid_plan_prices(apps, schema_editor):
    PaidPlan = apps.get_model("platform_web", "PaidPlan")

    price_map = {
        "Free": Decimal("0.00"),
        "Supporter": Decimal("9.99"),
        "I'm in love": Decimal("19.99"),
        "Top 1%": Decimal("29.99"),
    }

    for title, price in price_map.items():
        PaidPlan.objects.filter(title=title).update(price=price)


def revert_paid_plan_prices(apps, schema_editor):
    PaidPlan = apps.get_model("platform_web", "PaidPlan")
    PaidPlan.objects.filter(
        title__in=["Free", "Supporter", "I'm in love", "Top 1%"],
    ).update(price=None)


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0059_paidplan_price_paidplan_paidplan_price_non_negative"),
    ]

    operations = [
        migrations.RunPython(populate_paid_plan_prices, revert_paid_plan_prices),
    ]
