# Generated by Django 6.0.1 on 2026-06-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0061_paidplan_title_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paidplan',
            name='paidplan_title_unique',
        ),
        migrations.AlterField(
            model_name='paidplan',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
