# Generated by Django 6.0.1 on 2026-07-12 13:29

import platform_web.services.model.SlugService
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0062_remove_paidplan_paidplan_title_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.CharField(blank=True, help_text='Brief summary for preview/SEO. Auto-generated if left empty.', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-published_at', 'order'],
            },
            bases=(platform_web.services.model.SlugService.SlugService, models.Model),
        ),
    ]
