# Generated by Django 6.0.1 on 2026-09-02 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0065_alter_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering for admin sorting')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('projects', models.ManyToManyField(blank=True, help_text='Projects shown under this skill on the roadmap', related_name='skills', to='platform_web.project')),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='platform_web.course', verbose_name='Related course')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('related_course', 'name'), name='skill_name_unique_per_course')],
            },
        ),
    ]
