# Generated by Django 6.0.1 on 2026-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0066_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
