# Generated by Django 6.0.1 on 2026-09-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0067_project_skill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_job_course',
            field=models.BooleanField(default=False, help_text="Job-track course. Projects attach via skills, not as the project's home course.", verbose_name='Is job course'),
        ),
    ]
