# Generated by Django 6.0.1 on 2026-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0068_course_is_job_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programminglanguage",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
