# Generated by Django 6.0.1 on 2026-09-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0069_alter_programminglanguage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('topic', 'Topic'), ('project', 'Project'), ('workout', 'Workout'), ('concept', 'Concept')], default='project', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='related_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='platform_web.course', verbose_name='Course'),
        ),
    ]
