# Generated by Django 6.0.1 on 2026-10-03 12:47

from django.db import migrations, models


def copy_job_courses_forward(apps, schema_editor):
    Course = apps.get_model("platform_web", "Course")
    Course.objects.filter(is_job_course=True).update(type="job")


def copy_job_courses_backward(apps, schema_editor):
    Course = apps.get_model("platform_web", "Course")
    Course.objects.filter(type="job").update(is_job_course=True)
    Course.objects.exclude(type="job").update(is_job_course=False)


class Migration(migrations.Migration):

    dependencies = [
        ("platform_web", "0070_alter_project_type_alter_skill_related_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular course"),
                    ("language", "Language course"),
                    ("job", "Job course"),
                    ("guide", "Guide"),
                ],
                default="regular",
                max_length=20,
                verbose_name="Course type",
            ),
        ),
        migrations.RunPython(copy_job_courses_forward, copy_job_courses_backward),
        migrations.RemoveField(
            model_name="course",
            name="is_job_course",
        ),
    ]
