# Generated by Django 6.0.1 on 2026-10-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0071_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='contents',
            field=models.TextField(blank=True, default='', help_text='Numbered list shown under this skill on the course timeline when it has no projects.', verbose_name='Content'),
        ),
    ]
