# Generated by Django 6.0.1 on 2026-10-07 07:59

import platform_web.models.project.Course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_web', '0072_skill_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=platform_web.models.project.Course.course_image_upload_to, verbose_name='Image'),
        ),
    ]
